# This configuration tells Spring Boot DevTools to exclude certain packages
# from the "restart" classloader and load them with the "base" classloader instead.
# This is necessary for classes that are serialized and need to survive an
# application restart, preventing ClassCastExceptions.
restart.exclude.observatory=/dev/ikm/server/cosmos/observatory/.*