#Database Properties
ike.database.directory=${IKE_DB_DIRECTORY}
ike.database.datastoreType=${IKE_DB_TYPE}
cosmos.observatory.database.directory=${COSMOS_OBSERVATORY_DB_DIRECTORY}
cosmos.observatory.database.name=${COSMOS_OBSERVATORY_DB_NAME}
cosmos.constellation.database.directory=${COSMOS_CONSTELLATION_DB_DIRECTORY}
cosmos.constellation.database.name=${COSMOS_CONSTELLATION_DB_NAME}

#Neo4j Properties
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

#LangChain4j Properties
langchain4j.neo4j.uri=${NEO4J_URI}
langchain4j.neo4j.username=${NEO4J_USERNAME}
langchain4j.neo4j.password=${NEO4J_PASSWORD}
google.gemini.key=${GOOGLE_GEMINI_KEY}


#Spring Properties
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=ERROR
spring.devtools.restart.enabled=false

# Set the logging level for your application's packages.
# Levels are: TRACE, DEBUG, INFO, WARN, ERROR
# Setting it to DEBUG is great for development to see detailed flow.
logging.level.dev.ikm.server.cosmos=DEBUG
logging.level.org.springframework.data.neo4j.cypher=DEBUG
logging.level.org.neo4j.driver=DEBUG



#Thymeleaf
# Sets the location of the template files.
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false
# Sets the file extension of the templates.
spring.thymeleaf.suffix=.html
# Additional common properties
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8