#Database Properties
ike.database.directory=${IKE_DB_DIRECTORY}
ike.database.type=${IKE_DB_TYPE}
cosmos.scope.database.directory=${COSMOS_SCOPE_DB_DIRECTORY}
cosmos.scope.database.name=${COSMOS_SCOPE_DB_NAME}
cosmos.constellation.database.directory=${COSMOS_CONSTELLATION_DB_DIRECTORY}
cosmos.constellation.database.name=${COSMOS_CONSTELLATION_DB_NAME}


#Neo4j Properties
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

#Spring Properties
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

#Thymeleaf
# Sets the location of the template files.
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false
# Sets the file extension of the templates.
spring.thymeleaf.suffix=.html
# Additional common properties
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8