#Database Properties
# Cosmos Properties
cosmos.directory=${COSMOS_DIRECTORY}

#LangChain4j Properties
ollama.url=${OLLAMA_URL}
ollama.llm.model=${OLLAMA_LLM_MODEL}
ollama.embedding.model=${OLLAMA_EMBEDDING_MODEL}

#Spring Properties
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=ERROR
spring.devtools.restart.enabled=false

# Set the logging level for your application's packages.
# Levels are: TRACE, DEBUG, INFO, WARN, ERROR
# Setting it to DEBUG is great for development to see detailed flow.
logging.level.dev.ikm.server.cosmos=DEBUG
logging.level.org.neo4j.driver=DEBUG

#Thymeleaf
# Sets the location of the template files.
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false
# Sets the file extension of the templates.
spring.thymeleaf.suffix=.html
# Additional common properties
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8